"""Public API for single-instance, multi-frame 3D refinement."""

from trackrefinery.adapters import X4DInferenceExport, export_x4d_clip_inference
from trackrefinery.component_consensus import (
    COMPONENT_CONSENSUS_ALGORITHM_VERSION,
    COMPONENT_CONSENSUS_CONFIG_SCHEMA_VERSION,
    ComponentConsensusRefiner,
    ComponentConsensusSettings,
    aggregate_geometry_components,
    select_object_components,
)
from trackrefinery.contracts import (
    Box3D,
    FrameCloud,
    InstanceTrack,
    InsufficientEvidence,
    ObservationKind,
    Pose3D,
    RefinedFramePose,
    RefinementCase,
    RefinementOutcome,
    RefinementSuccess,
    TrackObservation,
)
from trackrefinery.dataset import InferenceDataset
from trackrefinery.evaluation import (
    AcceptanceThresholds,
    BenchmarkReport,
    EvaluationReport,
    evaluate_case,
    evaluate_suite,
)
from trackrefinery.geometric import (
    EVIDENCE_TRACE_CONTRACT,
    GEOMETRIC_ALGORITHM_VERSION,
    GEOMETRIC_CONFIG_SCHEMA_VERSION,
    AggregateSharpnessTrace,
    AnchoredAggregationTrace,
    CanonicalShapeTrace,
    CuboidFitTrace,
    EnvelopeFittingSettings,
    EvidenceSelectionSettings,
    EvidenceState,
    FrameComponentTrace,
    FrameEvidenceTrace,
    FrameRegistrationTrace,
    FrameRole,
    GeometricRefinementRun,
    GeometricRefinementSettings,
    GeometricRefinementTrace,
    GroundPlaneEstimate,
    JointCuboidRefiner,
    RegistrationSettings,
    fit_alternating_envelope,
    read_geometric_trace,
    register_canonical_shape,
    select_initial_evidence,
    validate_geometric_trace,
    write_geometric_trace,
)
from trackrefinery.refiner import TrackRefiner, validate_outcome
from trackrefinery.review import (
    build_clip_review_suite,
    build_review_bundle,
    build_review_suite,
)
from trackrefinery.serde import read_outcome, write_outcome
from trackrefinery.targets import GoldFramePose, GoldTarget, TargetDataset

__all__ = [
    "COMPONENT_CONSENSUS_ALGORITHM_VERSION",
    "COMPONENT_CONSENSUS_CONFIG_SCHEMA_VERSION",
    "EVIDENCE_TRACE_CONTRACT",
    "GEOMETRIC_ALGORITHM_VERSION",
    "GEOMETRIC_CONFIG_SCHEMA_VERSION",
    "AcceptanceThresholds",
    "AggregateSharpnessTrace",
    "AnchoredAggregationTrace",
    "BenchmarkReport",
    "Box3D",
    "CanonicalShapeTrace",
    "ComponentConsensusRefiner",
    "ComponentConsensusSettings",
    "CuboidFitTrace",
    "EnvelopeFittingSettings",
    "EvaluationReport",
    "EvidenceSelectionSettings",
    "EvidenceState",
    "FrameCloud",
    "FrameComponentTrace",
    "FrameEvidenceTrace",
    "FrameRegistrationTrace",
    "FrameRole",
    "GeometricRefinementRun",
    "GeometricRefinementSettings",
    "GeometricRefinementTrace",
    "GoldFramePose",
    "GoldTarget",
    "GroundPlaneEstimate",
    "InferenceDataset",
    "InstanceTrack",
    "InsufficientEvidence",
    "JointCuboidRefiner",
    "ObservationKind",
    "Pose3D",
    "RefinedFramePose",
    "RefinementCase",
    "RefinementOutcome",
    "RefinementSuccess",
    "RegistrationSettings",
    "TargetDataset",
    "TrackObservation",
    "TrackRefiner",
    "X4DInferenceExport",
    "aggregate_geometry_components",
    "build_clip_review_suite",
    "build_review_bundle",
    "build_review_suite",
    "evaluate_case",
    "evaluate_suite",
    "export_x4d_clip_inference",
    "fit_alternating_envelope",
    "read_geometric_trace",
    "read_outcome",
    "register_canonical_shape",
    "select_initial_evidence",
    "select_object_components",
    "validate_geometric_trace",
    "validate_outcome",
    "write_geometric_trace",
    "write_outcome",
]

__version__ = "0.1.0.dev0"
